name: mcgill
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - xarray
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - openpyxl
  - netcdf4
  - cartopy
  - gsw
  - ffmpeg
  - numba
variables:
  KMP_DUPLICATE_LIB_OK: 'TRUE'